### ISSUE TITLE
添加商品的bug

### ISSUE THREAD

**Issue by walkenzhong** [kmahyyg/shit-ssm-eshop#16]
添加商品时，要是商品已经存在购物车里面，那不管怎么添加，显示在购物车里面的数量始终为1，感觉应该先检查当前商品是否存在在购物车里面，若存在则增加商品数量（不管购物车页面可以直接修改商品数量，所以也可以忽略，不算是安全问题）

**Comment by kmahyyg** [comment]
刚刚认真运行了一下整个流程，大概明白你的意思了。不做加减了，做了复杂度就上去了，这个试验项目就暂时不做了，让用户自己去下单页面改购物车里的商品数量算了。

Won't fix.
